import {
  Anchor,
  Award,
  Axe,
  Badge,
  Bird,
  Bomb,
  BookMarked,
  CircleDot,
  Clover,
  Compass,
  Crown,
  Crosshair,
  Diamond,
  Dices,
  Dog,
  Drama,
  Dumbbell,
  Eye,
  Fish,
  Flag,
  Flame,
  FlameKindling,
  Footprints,
  Gamepad2,
  Gem,
  Ghost,
  Globe,
  Goal,
  Guitar,
  Hammer,
  Heart,
  Hexagon,
  Joystick,
  Leaf,
  MapPin,
  Medal,
  Megaphone,
  Moon,
  Mountain,
  Music,
  Octagon,
  Palette,
  PawPrint,
  Pentagon,
  Pickaxe,
  Plane,
  Radar,
  Rainbow,
  Rocket,
  Sailboat,
  Shield,
  ShieldCheck,
  Ship,
  Skull,
  Sparkles,
  Spade,
  Star,
  Sun,
  Swords,
  Target,
  Tent,
  Ticket,
  TrainFront,
  TreePine,
  Trophy,
  Turtle,
  Users,
  VenetianMask,
  Volleyball,
  Wrench,
  Zap,
  type LucideIcon,
} from 'lucide-react'

export const SQUAD_ICON_KEYS = [
  'anchor',
  'award',
  'axe',
  'badge',
  'bird',
  'bomb',
  'bookmark',
  'bullseye',
  'clover',
  'compass',
  'crown',
  'crosshair',
  'diamond',
  'dice',
  'dog',
  'drama',
  'dumbbell',
  'eye',
  'fish',
  'flag',
  'flame',
  'flame-kindling',
  'footprints',
  'gamepad',
  'gem',
  'ghost',
  'globe',
  'goal',
  'guitar',
  'hammer',
  'heart',
  'hexagon',
  'joystick',
  'leaf',
  'map-pin',
  'medal',
  'megaphone',
  'moon',
  'mountain',
  'music',
  'octagon',
  'palette',
  'paw',
  'pentagon',
  'pickaxe',
  'plane',
  'radar',
  'rainbow',
  'rocket',
  'sailboat',
  'shield',
  'shield-check',
  'ship',
  'skull',
  'sparkles',
  'spade',
  'star',
  'sun',
  'swords',
  'target',
  'tent',
  'ticket',
  'train',
  'tree',
  'trophy',
  'turtle',
  'users',
  'mask',
  'volleyball',
  'wrench',
  'zap',
] as const

export type SquadIconKey = (typeof SQUAD_ICON_KEYS)[number]

export const squadIconRegistry: Record<SquadIconKey, LucideIcon> = {
  anchor: Anchor,
  award: Award,
  axe: Axe,
  badge: Badge,
  bird: Bird,
  bomb: Bomb,
  bookmark: BookMarked,
  bullseye: CircleDot,
  clover: Clover,
  compass: Compass,
  crown: Crown,
  crosshair: Crosshair,
  diamond: Diamond,
  dice: Dices,
  dog: Dog,
  drama: Drama,
  dumbbell: Dumbbell,
  eye: Eye,
  fish: Fish,
  flag: Flag,
  flame: Flame,
  'flame-kindling': FlameKindling,
  footprints: Footprints,
  gamepad: Gamepad2,
  gem: Gem,
  ghost: Ghost,
  globe: Globe,
  goal: Goal,
  guitar: Guitar,
  hammer: Hammer,
  heart: Heart,
  hexagon: Hexagon,
  joystick: Joystick,
  leaf: Leaf,
  'map-pin': MapPin,
  medal: Medal,
  megaphone: Megaphone,
  moon: Moon,
  mountain: Mountain,
  music: Music,
  octagon: Octagon,
  palette: Palette,
  paw: PawPrint,
  pentagon: Pentagon,
  pickaxe: Pickaxe,
  plane: Plane,
  radar: Radar,
  rainbow: Rainbow,
  rocket: Rocket,
  sailboat: Sailboat,
  shield: Shield,
  'shield-check': ShieldCheck,
  ship: Ship,
  skull: Skull,
  sparkles: Sparkles,
  spade: Spade,
  star: Star,
  sun: Sun,
  swords: Swords,
  target: Target,
  tent: Tent,
  ticket: Ticket,
  train: TrainFront,
  tree: TreePine,
  trophy: Trophy,
  turtle: Turtle,
  users: Users,
  mask: VenetianMask,
  volleyball: Volleyball,
  wrench: Wrench,
  zap: Zap,
}

export const squadIconLabels: Record<SquadIconKey, string> = {
  anchor: 'Anchor',
  award: 'Award',
  axe: 'Axe',
  badge: 'Badge',
  bird: 'Bird',
  bomb: 'Bomb',
  bookmark: 'Bookmark',
  bullseye: 'Bullseye',
  clover: 'Clover',
  compass: 'Compass',
  crown: 'Crown',
  crosshair: 'Crosshair',
  diamond: 'Diamond',
  dice: 'Dice',
  dog: 'Dog',
  drama: 'Theatre',
  dumbbell: 'Strength',
  eye: 'Eye',
  fish: 'Fish',
  flag: 'Flag',
  flame: 'Flame',
  'flame-kindling': 'Campfire',
  footprints: 'Tracks',
  gamepad: 'Gaming',
  gem: 'Gem',
  ghost: 'Ghost',
  globe: 'Globe',
  goal: 'Goal',
  guitar: 'Guitar',
  hammer: 'Hammer',
  heart: 'Heart',
  hexagon: 'Hexagon',
  joystick: 'Joystick',
  leaf: 'Leaf',
  'map-pin': 'Location',
  medal: 'Medal',
  megaphone: 'Megaphone',
  moon: 'Moon',
  mountain: 'Mountain',
  music: 'Music',
  octagon: 'Octagon',
  palette: 'Palette',
  paw: 'Paw',
  pentagon: 'Pentagon',
  pickaxe: 'Pickaxe',
  plane: 'Plane',
  radar: 'Radar',
  rainbow: 'Rainbow',
  rocket: 'Rocket',
  sailboat: 'Sailboat',
  shield: 'Shield',
  'shield-check': 'Shield check',
  ship: 'Ship',
  skull: 'Skull',
  sparkles: 'Sparkles',
  spade: 'Spade',
  star: 'Star',
  sun: 'Sun',
  swords: 'Swords',
  target: 'Target',
  tent: 'Tent',
  ticket: 'Ticket',
  train: 'Train',
  tree: 'Tree',
  trophy: 'Trophy',
  turtle: 'Turtle',
  users: 'Team',
  mask: 'Mask',
  volleyball: 'Volleyball',
  wrench: 'Wrench',
  zap: 'Bolt',
}

export const DEFAULT_SQUAD_ICON: SquadIconKey = 'users'

export function isSquadIconKey(value: string): value is SquadIconKey {
  return (SQUAD_ICON_KEYS as readonly string[]).includes(value)
}

export function getSquadIcon(key: string): LucideIcon {
  if (isSquadIconKey(key)) {
    return squadIconRegistry[key]
  }

  return squadIconRegistry[DEFAULT_SQUAD_ICON]
}
