/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as protectedLayoutRouteImport } from './routes/(protected)/_layout'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as protectedLayoutTestRouteImport } from './routes/(protected)/_layout.test'
import { Route as protectedLayoutSettingsRouteImport } from './routes/(protected)/_layout.settings'
import { Route as protectedLayoutPatchNotesRouteImport } from './routes/(protected)/_layout.patch-notes'
import { Route as protectedLayoutMatchRouteImport } from './routes/(protected)/_layout.match'
import { Route as protectedLayoutHelpRouteImport } from './routes/(protected)/_layout.help'
import { Route as protectedLayoutFriendsRouteImport } from './routes/(protected)/_layout.friends'
import { Route as protectedLayoutClubsRouteImport } from './routes/(protected)/_layout.clubs'
import { Route as protectedLayoutMatchIndexRouteImport } from './routes/(protected)/_layout.match.index'
import { Route as protectedLayoutClubsIndexRouteImport } from './routes/(protected)/_layout.clubs.index'
import { Route as protectedLayoutMatchMatchIdRouteImport } from './routes/(protected)/_layout.match.$matchId'
import { Route as protectedLayoutClubsClubRouteImport } from './routes/(protected)/_layout.clubs.$club'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedLayoutRoute = protectedLayoutRouteImport.update({
  id: '/(protected)/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedLayoutTestRoute = protectedLayoutTestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => protectedLayoutRoute,
} as any)
const protectedLayoutSettingsRoute = protectedLayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => protectedLayoutRoute,
} as any)
const protectedLayoutPatchNotesRoute =
  protectedLayoutPatchNotesRouteImport.update({
    id: '/patch-notes',
    path: '/patch-notes',
    getParentRoute: () => protectedLayoutRoute,
  } as any)
const protectedLayoutMatchRoute = protectedLayoutMatchRouteImport.update({
  id: '/match',
  path: '/match',
  getParentRoute: () => protectedLayoutRoute,
} as any)
const protectedLayoutHelpRoute = protectedLayoutHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => protectedLayoutRoute,
} as any)
const protectedLayoutFriendsRoute = protectedLayoutFriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => protectedLayoutRoute,
} as any)
const protectedLayoutClubsRoute = protectedLayoutClubsRouteImport.update({
  id: '/clubs',
  path: '/clubs',
  getParentRoute: () => protectedLayoutRoute,
} as any)
const protectedLayoutMatchIndexRoute =
  protectedLayoutMatchIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => protectedLayoutMatchRoute,
  } as any)
const protectedLayoutClubsIndexRoute =
  protectedLayoutClubsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => protectedLayoutClubsRoute,
  } as any)
const protectedLayoutMatchMatchIdRoute =
  protectedLayoutMatchMatchIdRouteImport.update({
    id: '/$matchId',
    path: '/$matchId',
    getParentRoute: () => protectedLayoutMatchRoute,
  } as any)
const protectedLayoutClubsClubRoute =
  protectedLayoutClubsClubRouteImport.update({
    id: '/$club',
    path: '/$club',
    getParentRoute: () => protectedLayoutClubsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/clubs': typeof protectedLayoutClubsRouteWithChildren
  '/friends': typeof protectedLayoutFriendsRoute
  '/help': typeof protectedLayoutHelpRoute
  '/match': typeof protectedLayoutMatchRouteWithChildren
  '/patch-notes': typeof protectedLayoutPatchNotesRoute
  '/settings': typeof protectedLayoutSettingsRoute
  '/test': typeof protectedLayoutTestRoute
  '/clubs/$club': typeof protectedLayoutClubsClubRoute
  '/match/$matchId': typeof protectedLayoutMatchMatchIdRoute
  '/clubs/': typeof protectedLayoutClubsIndexRoute
  '/match/': typeof protectedLayoutMatchIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/friends': typeof protectedLayoutFriendsRoute
  '/help': typeof protectedLayoutHelpRoute
  '/patch-notes': typeof protectedLayoutPatchNotesRoute
  '/settings': typeof protectedLayoutSettingsRoute
  '/test': typeof protectedLayoutTestRoute
  '/clubs/$club': typeof protectedLayoutClubsClubRoute
  '/match/$matchId': typeof protectedLayoutMatchMatchIdRoute
  '/clubs': typeof protectedLayoutClubsIndexRoute
  '/match': typeof protectedLayoutMatchIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(protected)/_layout': typeof protectedLayoutRouteWithChildren
  '/(protected)/_layout/clubs': typeof protectedLayoutClubsRouteWithChildren
  '/(protected)/_layout/friends': typeof protectedLayoutFriendsRoute
  '/(protected)/_layout/help': typeof protectedLayoutHelpRoute
  '/(protected)/_layout/match': typeof protectedLayoutMatchRouteWithChildren
  '/(protected)/_layout/patch-notes': typeof protectedLayoutPatchNotesRoute
  '/(protected)/_layout/settings': typeof protectedLayoutSettingsRoute
  '/(protected)/_layout/test': typeof protectedLayoutTestRoute
  '/(protected)/_layout/clubs/$club': typeof protectedLayoutClubsClubRoute
  '/(protected)/_layout/match/$matchId': typeof protectedLayoutMatchMatchIdRoute
  '/(protected)/_layout/clubs/': typeof protectedLayoutClubsIndexRoute
  '/(protected)/_layout/match/': typeof protectedLayoutMatchIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/sign-in'
    | '/sign-up'
    | '/clubs'
    | '/friends'
    | '/help'
    | '/match'
    | '/patch-notes'
    | '/settings'
    | '/test'
    | '/clubs/$club'
    | '/match/$matchId'
    | '/clubs/'
    | '/match/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/sign-in'
    | '/sign-up'
    | '/friends'
    | '/help'
    | '/patch-notes'
    | '/settings'
    | '/test'
    | '/clubs/$club'
    | '/match/$matchId'
    | '/clubs'
    | '/match'
  id:
    | '__root__'
    | '/'
    | '/(auth)/forgot-password'
    | '/(auth)/sign-in'
    | '/(auth)/sign-up'
    | '/(protected)/_layout'
    | '/(protected)/_layout/clubs'
    | '/(protected)/_layout/friends'
    | '/(protected)/_layout/help'
    | '/(protected)/_layout/match'
    | '/(protected)/_layout/patch-notes'
    | '/(protected)/_layout/settings'
    | '/(protected)/_layout/test'
    | '/(protected)/_layout/clubs/$club'
    | '/(protected)/_layout/match/$matchId'
    | '/(protected)/_layout/clubs/'
    | '/(protected)/_layout/match/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authSignInRoute: typeof authSignInRoute
  authSignUpRoute: typeof authSignUpRoute
  protectedLayoutRoute: typeof protectedLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/_layout': {
      id: '/(protected)/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof protectedLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/_layout/test': {
      id: '/(protected)/_layout/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof protectedLayoutTestRouteImport
      parentRoute: typeof protectedLayoutRoute
    }
    '/(protected)/_layout/settings': {
      id: '/(protected)/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof protectedLayoutSettingsRouteImport
      parentRoute: typeof protectedLayoutRoute
    }
    '/(protected)/_layout/patch-notes': {
      id: '/(protected)/_layout/patch-notes'
      path: '/patch-notes'
      fullPath: '/patch-notes'
      preLoaderRoute: typeof protectedLayoutPatchNotesRouteImport
      parentRoute: typeof protectedLayoutRoute
    }
    '/(protected)/_layout/match': {
      id: '/(protected)/_layout/match'
      path: '/match'
      fullPath: '/match'
      preLoaderRoute: typeof protectedLayoutMatchRouteImport
      parentRoute: typeof protectedLayoutRoute
    }
    '/(protected)/_layout/help': {
      id: '/(protected)/_layout/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof protectedLayoutHelpRouteImport
      parentRoute: typeof protectedLayoutRoute
    }
    '/(protected)/_layout/friends': {
      id: '/(protected)/_layout/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof protectedLayoutFriendsRouteImport
      parentRoute: typeof protectedLayoutRoute
    }
    '/(protected)/_layout/clubs': {
      id: '/(protected)/_layout/clubs'
      path: '/clubs'
      fullPath: '/clubs'
      preLoaderRoute: typeof protectedLayoutClubsRouteImport
      parentRoute: typeof protectedLayoutRoute
    }
    '/(protected)/_layout/match/': {
      id: '/(protected)/_layout/match/'
      path: '/'
      fullPath: '/match/'
      preLoaderRoute: typeof protectedLayoutMatchIndexRouteImport
      parentRoute: typeof protectedLayoutMatchRoute
    }
    '/(protected)/_layout/clubs/': {
      id: '/(protected)/_layout/clubs/'
      path: '/'
      fullPath: '/clubs/'
      preLoaderRoute: typeof protectedLayoutClubsIndexRouteImport
      parentRoute: typeof protectedLayoutClubsRoute
    }
    '/(protected)/_layout/match/$matchId': {
      id: '/(protected)/_layout/match/$matchId'
      path: '/$matchId'
      fullPath: '/match/$matchId'
      preLoaderRoute: typeof protectedLayoutMatchMatchIdRouteImport
      parentRoute: typeof protectedLayoutMatchRoute
    }
    '/(protected)/_layout/clubs/$club': {
      id: '/(protected)/_layout/clubs/$club'
      path: '/$club'
      fullPath: '/clubs/$club'
      preLoaderRoute: typeof protectedLayoutClubsClubRouteImport
      parentRoute: typeof protectedLayoutClubsRoute
    }
  }
}

interface protectedLayoutClubsRouteChildren {
  protectedLayoutClubsClubRoute: typeof protectedLayoutClubsClubRoute
  protectedLayoutClubsIndexRoute: typeof protectedLayoutClubsIndexRoute
}

const protectedLayoutClubsRouteChildren: protectedLayoutClubsRouteChildren = {
  protectedLayoutClubsClubRoute: protectedLayoutClubsClubRoute,
  protectedLayoutClubsIndexRoute: protectedLayoutClubsIndexRoute,
}

const protectedLayoutClubsRouteWithChildren =
  protectedLayoutClubsRoute._addFileChildren(protectedLayoutClubsRouteChildren)

interface protectedLayoutMatchRouteChildren {
  protectedLayoutMatchMatchIdRoute: typeof protectedLayoutMatchMatchIdRoute
  protectedLayoutMatchIndexRoute: typeof protectedLayoutMatchIndexRoute
}

const protectedLayoutMatchRouteChildren: protectedLayoutMatchRouteChildren = {
  protectedLayoutMatchMatchIdRoute: protectedLayoutMatchMatchIdRoute,
  protectedLayoutMatchIndexRoute: protectedLayoutMatchIndexRoute,
}

const protectedLayoutMatchRouteWithChildren =
  protectedLayoutMatchRoute._addFileChildren(protectedLayoutMatchRouteChildren)

interface protectedLayoutRouteChildren {
  protectedLayoutClubsRoute: typeof protectedLayoutClubsRouteWithChildren
  protectedLayoutFriendsRoute: typeof protectedLayoutFriendsRoute
  protectedLayoutHelpRoute: typeof protectedLayoutHelpRoute
  protectedLayoutMatchRoute: typeof protectedLayoutMatchRouteWithChildren
  protectedLayoutPatchNotesRoute: typeof protectedLayoutPatchNotesRoute
  protectedLayoutSettingsRoute: typeof protectedLayoutSettingsRoute
  protectedLayoutTestRoute: typeof protectedLayoutTestRoute
}

const protectedLayoutRouteChildren: protectedLayoutRouteChildren = {
  protectedLayoutClubsRoute: protectedLayoutClubsRouteWithChildren,
  protectedLayoutFriendsRoute: protectedLayoutFriendsRoute,
  protectedLayoutHelpRoute: protectedLayoutHelpRoute,
  protectedLayoutMatchRoute: protectedLayoutMatchRouteWithChildren,
  protectedLayoutPatchNotesRoute: protectedLayoutPatchNotesRoute,
  protectedLayoutSettingsRoute: protectedLayoutSettingsRoute,
  protectedLayoutTestRoute: protectedLayoutTestRoute,
}

const protectedLayoutRouteWithChildren = protectedLayoutRoute._addFileChildren(
  protectedLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authSignInRoute: authSignInRoute,
  authSignUpRoute: authSignUpRoute,
  protectedLayoutRoute: protectedLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
